title: "Buttons"
description: |
  The buttons use our primary colour to draw attention and stand out. Each button has a specific purpose:
patterns:
  basic:
    title: "Basic"
    description: |
      Basic button to be used accross the different mediums when a regular button is needed
  ghost:
    title: "Ghost"
    description: |
      The Ghost button is to be used for navigation bar
  accent:
    title: "Accent"
    description: |
      Accent buttons are to be used as save buttons
  accent-ghost:
    title: "Accent ghost"
    description: |
      Accent Ghost are to be used as a contrast against the basic button. It is to be used as a secondary alternative action button.
  build-btn:
    title: "Build recipe link"
    description: |
      Accent buttons are to be used as save buttons
  mission-btn:
    title: "Start mission/Abort mission button"
    description: |
      Accent Ghost are to be used as a contrast against the basic button. It is to be used as a secondary alternative action button.
  remove-btn:
    title: "Remove array-list item button"
    description: |
      Accent Ghost are to be used as a contrast against the basic button. It is to be used as a secondary alternative action button.
